name: Model Calibration on Push to Main

on:
  workflow_run:
    workflows: ["Model Training on Push to Main"]
    types:
      - completed
    branches:
      - main

jobs:
  calibrate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Pull Latest Changes from Training
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git pull origin main

    - name: Find Latest Model Timestamp
      run: |
        latest_model=$(ls -t models/model_*_base.joblib 2>/dev/null | head -n1)
        if [ -z "$latest_model" ]; then
          echo "ERROR: No base model found!"
          exit 1
        fi
        timestamp=$(echo $latest_model | sed 's/models\/model_//' | sed 's/_base.joblib//')
        echo "Found model with timestamp: $timestamp"
        echo "$timestamp" > timestamp.txt

    - name: Set File Permissions
      run: chmod +x ./src/calibrate_model.py ./src/evaluate_model.py

    - name: Calibrate Model Probabilities
      run: |
        timestamp=$(cat timestamp.txt)
        python ./src/calibrate_model.py --timestamp "$timestamp" --method sigmoid

    - name: Move Calibrated Model to models directory
      run: |
        timestamp=$(cat timestamp.txt)
        mv model_${timestamp}_calibrated_sigmoid.joblib models/
        mv calibration_report_${timestamp}.pickle models/

    - name: Evaluate Calibrated Model
      run: |
        timestamp=$(cat timestamp.txt)
        python ./src/evaluate_model.py --timestamp "$timestamp" --model-type calibrated
        mkdir -p metrics
        mv ${timestamp}_calibrated_metrics.json metrics/

    - name: Commit and Push Calibrated Model
      run: |
        timestamp=$(cat timestamp.txt)
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add models/model_${timestamp}_calibrated_sigmoid.joblib
        git add models/calibration_report_${timestamp}.pickle
        git add metrics/${timestamp}_calibrated_metrics.json
        git commit -m "Calibrate SVM model - ${timestamp}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}